apiVersion: v1
kind: Service
metadata:
  name: budget-service
spec:
  selector:
    app: budget-frontend
    ports:
      - protocol: "TCP"
        port: 6000
        targetport: 5000
    type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-frontend
spec:
  selector:
    matchLabels:
      app: budget-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: budget-frontend
    spec:
      containers:
      - name: budget-frontend
        image: dockerhub-url
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      - name: budget-backend
        image: dockerhub-url
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000


